TemperatureTable:
  Type: AWS::DynamoDB::Table
  Properties:
    KeySchema:
      - AttributeName: time
        KeyType: HASH
    AttributeDefinitions:
      - AttributeName: time
        AttributeType: S
    BillingMode: PAY_PER_REQUEST
    TableName: ${self:custom.tableName}



# you can add CloudFormation resource templates here
#resources:
#  Resources:
#    NewResource:
#      Type: AWS::S3::Bucket
#      Properties:
#        BucketName: my-new-bucket
#  Outputs:
#     NewOutput:
#       Description: "Description for the output"
#       Value: "Some output value"
